kind: pipeline
name: default

steps:
- name: web
  image: node:11-alpine
  commands:
  - cd ./packages/web
  - pwd
  - npm install
  - cat ./node_modules/ts-jest/package.json
  - ls -la .
  - npm run test

- name: node
  image: node:11-alpine
  commands:
  - cd ./packages/node
  - pwd
  - npm install
  - cat ./node_modules/ts-jest/package.json
  - ls -la .
  - npm run test

trigger:
  event: push
