kind: pipeline
name: default

steps:
- name: web
  image: node:11-alpine
  commands:
  - cd ./packages/web
  - npm run validate

- name: node
  image: node:11-alpine
  commands:
  - cd ./packages/node
  - npm run validate

trigger:
  event: push
