name: WIP

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - uses: embano1/wip@v1
        with:
          ghtoken: ${{ secrets.GITHUB_TOKEN }}
